package:
  name: gromacs
  version: 2018.6

build:
  number: 0

source:
  url: http://ftp.gromacs.org/pub/gromacs/gromacs-2018.6.tar.gz
  md5: 997f2b8108197780d61b23b5eb05644a

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - binutils
    - cmake
    - plumed =2.5.1
    - python
  host:
    - fftw
    - libhwloc 1.*
  run:
    - fftw
    - libhwloc 1.*
    - plumed >=2

test:
  commands:
    - gmx -version
    - gmx mdrun -h | grep plumed

about:
  home: http://www.gromacs.org/
  license: GNU Lesser General Public License (LGPL)
  summary: GROMACS is a versatile package to perform molecular dynamics.

