os:
  - linux
  - osx

env:
  - PACKAGE=plumed
  - PACKAGE=gromacs
  - PACKAGE=lammps

install:
  - curl -LO https://raw.githubusercontent.com/GiovanniBussi/conda-ci/master/conda-ci
  - source ./conda-ci install
  - export MAKEFLAGS=-j4
  - export CONDA_LABEL=lugano
# the conda channel:
  - export CONDA_USER=plumed 
  - if [[ -n $TRAVIS_REPO_SLUG ]] ; then
      CONDA_USER=${TRAVIS_REPO_SLUG%/*} ;
    fi

script:
  - conda-build -c conda-forge $PACKAGE

after_success:
  - if [[ -n $CONDA_UPLOAD_TOKEN ]]; then
      anaconda -t $CONDA_UPLOAD_TOKEN upload -u $CONDA_USER -l $CONDA_LABEL $CONDA_HOME/conda-bld/$TRAVIS_OS_NAME-64/$PACKAGE*.tar.bz2 --force ;
    fi
