language: cpp
matrix:
  include:
# linux conda package
  - name: GROMACS on Linux
    os: linux
    dist: trusty
    sudo: required
    env: PACKAGE=gromacs
# osx conda package
  - name: GROMACS on MacOS
    os: osx
    osx_image: xcode6.4
    env: PACKAGE=gromacs
install:
  - export CONDA_HOME=/var/tmp/miniconda
  - export PATH="$CONDA_HOME/bin:$PATH"
  - export CPU_COUNT=4
  - export CONDA_LABEL=lugano
  - ./run-conda-install.sh
script:
  - ./run-conda-build.sh $PACKAGE
after_success:
  - ./run-conda-upload.sh $PACKAGE
