os:
  - linux
  - osx

env:
  - PACKAGE=gromacs
  - PACKAGE=lammps

install:
  - export CONDA_HOME=/var/tmp/miniconda
  - export PATH="$CONDA_HOME/bin:$PATH"
  - export CPU_COUNT=4
  - export CONDA_LABEL=lugano
  - ./run-conda-install.sh

script:
  - ./run-conda-build.sh $PACKAGE

after_success:
  - ./run-conda-upload.sh $PACKAGE
